version: "3"
services:
    web:
        build: 
            context: .
            dockerfile: DevSkill.Inventory.Web/Dockerfile
        image: inventory-image
        env_file: 
            - web.env
        volumes:
            - inventory-data:/app/Logs
        ports:
            - "8000:80"
        entrypoint: ["dotnet", "DevSkill.Inventory.Web.dll"]
volumes:
    inventory-data:
      external: true